spring.application.name=neosuplex-api

# Conexión principal
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Forzar a Hibernate a reconocer MySQL sin pedir metadata
spring.jpa.database=MYSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Pool de conexiones (mantenemos lo que ya pusimos)
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=1