spring.application.name=neosuplex-api

# Cambiamos esta línea para que use solo la variable DB_URL:
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Limitar el pool de conexiones (máximo 3 para no exceder las 5 permitidas por el plan gratuito de Clever Cloud)
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=1
spring.datasource.hikari.connection-timeout=20000